// lib/case-data.ts
import { ICaseFile } from '../types';

export const caseData: ICaseFile = {
  'mansao-montes': {
    title: 'O Mistério da Mansão Montês',
    clientMessage: 'Prezado(a) Detetive,\n\nMeu nome é James Montês. Minha mãe, Darlene, foi encontrada morta na noite de sexta-feira. A polícia está tratando como uma investigação complexa, mas para mim, é simples: um dos meus familiares a matou. A ganância e os ressentimentos nesta casa são tão espessos quanto as paredes de pedra. Eles podem enganar a polícia com suas máscaras de luto, mas não a mim. E, espero, não a você. Envio os dossiês iniciais que consegui reunir. Por favor, descubra a verdade. O dinheiro não é problema.',
    suspects: [
      { id: 'ricardo', name: 'Ricardo Montês', profile: 'Ambicioso e implacável. Sempre teve uma relação conflituosa com a mãe sobre os rumos da empresa. Ele é o principal herdeiro do império Montês.', alibi: 'Afirma que estava em seu escritório na ala oeste, trabalhando em uma proposta de fusão das 20:00 até por volta das 23:30.' },
      { id: 'veronica', name: 'Verônica Montês', profile: 'A "ovelha negra" da família. Foi deserdada por Darlene há cinco anos após um escândalo envolvendo dívidas de jogo. Voltou à mansão recentemente.', alibi: 'Diz que passou a noite em seu antigo quarto, no segundo andar, lendo. Alega ter descido para a cozinha por volta das 21:30 para pegar um copo d\'água.' },
      { id: 'sofia', name: 'Sofia Montês', profile: 'Extremamente preocupada com a imagem e o status social. Sentia-se constantemente diminuída e controlada por Darlene. Tem grande interesse nos jardins da mansão.', alibi: 'Estava na estufa, nos fundos da propriedade. Saiu de lá por volta das 22:00 e depois ficou no salão principal lendo uma revista.' },
      { id: 'afonso', name: 'Afonso Pereira', profile: 'Leal, discreto e aparentemente devotado a Darlene. Conhece todos os segredos da família. Sua filha adoeceu e Darlene se recusou a lhe dar um adiantamento.', alibi: 'Serviu o chá de camomila para Darlene às 21:05. Depois, retirou-se para a copa, onde permaneceu organizando a prataria.' },
      { id: 'james', name: 'James Montês', profile: 'O filho "artista". Sempre se sentiu à sombra dos irmãos e da mãe. Embora pareça distante dos negócios, tem um profundo ressentimento por nunca ter sido levado a sério.', alibi: 'Alega que estava em seu estúdio de pintura no anexo da propriedade, das 20:00 até encontrar o corpo da mãe por volta das 23:15.' },
      { id: 'henrique', name: 'Dr. Henrique Bastos', profile: 'Advogado da família há décadas, conhece todos os segredos financeiros. Estava em processo de reestruturação do testamento de Darlene.', alibi: 'Esteve na mansão para uma reunião com Darlene que terminou às 20:00. Afirma ter ido direto para sua casa.' },
      { id: 'arthur', name: 'Arthur Vasconcelos', profile: 'Um empresário concorrente que estava à beira da ruína por causa de Darlene, que descobriu uma fraude em suas contas.', alibi: 'Admite ter ido à mansão para uma última tentativa de negociação, saindo "frustrado" às 19:00. Diz que foi a um bar depois, sozinho.' },
      { id: 'leonardo', name: 'Leonardo Aguilar', profile: 'Um jovem artista que Darlene apadrinhou. A relação azedou recentemente e Darlene ameaçou cortar seu financiamento.', alibi: 'Nega estar na mansão. Afirma que estava em seu apartamento no centro da cidade. Ninguém pode confirmar.' },
      { id: 'clara', name: 'Clara Dias', profile: 'A cuidadora particular de Darlene, responsável por seus medicamentos. Foi repreendida por Darlene por "pequenos descuidos" na semana do crime.', alibi: 'Terminou seu turno às 20:30. Diz que foi para seu quarto na ala dos funcionários e não saiu até a manhã seguinte.' },
    ],
    evidence: [
        { id: '2A', title: 'O Diário da Cidade', content: 'MORRE DARLENE MONTÊS, PILAR DA ALTA SOCIEDADE\nDarlene Montês, 68, a poderosa matriarca da família Montês e presidente do conselho das Empresas Montês, foi encontrada sem vida em sua mansão na noite de ontem. A causa da morte ainda não foi divulgada oficialmente, mas fontes próximas à investigação não descartam a possibilidade de crime. A família, conhecida por seu império industrial e por sua discrição, está em luto. Darlene deixa três filhos: Ricardo, o atual CEO, Verônica e James. A polícia iniciou os interrogatórios com os residentes da mansão.' },
        { id: '2B', title: 'Coluna Social - "Olho da Elite"', content: 'TENSÃO NA MANSÃO MONTÊS ANTES DA TRAGÉDIA\nEnquanto a cidade lamenta a perda de Darlene Montês, fontes desta coluna afirmam que o clima na mansão era tudo, menos pacífico. Uma acalorada discussão entre Darlene e seu filho Ricardo teria sido ouvida na tarde de sexta-feira, supostamente sobre uma "venda hostil" que a matriarca vetou. Além disso, a recente reaproximação da filha pródiga, Verônica, cujas dívidas são notórias, já causava burburinho. Uma fonte anônima garante: "Aquela casa era um barril de pólvora. A morte de Darlene foi a explosão."' },
        { id: '2C', title: 'Laudo Pericial - Causa da Morte', content: 'LAUDO Nº 734.\nVÍTIMA: Darlene Montês, 68 anos.\nCONCLUSÃO: Causa da morte determinada como envenenamento por parada cardiorrespiratória induzida pela ingestão de glicosídeos cardíacos, consistentes com a toxina encontrada na planta Nerium oleander (Oleandro). Hora estimada do óbito: Sexta-feira, 14/06, entre 21:00 e 23:00.' },
        { id: '2D', title: 'Laudo Pericial - Análise da Cena do Crime', content: 'Nenhum sinal de arrombamento ou luta na Biblioteca. Uma xícara de chá e um pires foram encontrados sobre a mesa auxiliar. Análise da porcelana indica ser uma réplica de alta qualidade do famoso jogo de chá chinês da família, mas não uma peça original do conjunto pertencente à vítima.' },
        { id: '2E', title: 'Laudo Pericial - Impressões Digitais', content: 'Locais analisados:\n\nXícara de chá: Impressões de Darlene Montês e Afonso Pereira.\nPires: Impressões de Darlene Montês e Afonso Pereira.\nMaçaneta interna da porta da biblioteca: Impressões de Darlene, Afonso, Ricardo e James Montês.' },
        { id: '2F', title: 'Depoimento - Jardineiro (Hélio)', content: 'Eu cuido dos jardins há 15 anos. O arbusto de Oleandro perto da estufa é lindo, mas sei que é venenosíssimo. Notei no sábado de manhã que vários galhos pequenos foram cortados ou arrancados de forma grosseira. Ninguém além de mim e da Sra. Sofia costuma mexer nas plantas daquela área.' },
        { id: '2G', title: 'Registro de Segurança - Log da Portaria (14/06)', content: '17:55 - ENTRADA: Dr. Henrique Bastos\n18:30 - ENTRADA: Arthur Vasconcelos\n19:05 - SAÍDA: Arthur Vasconcelos\n20:10 - SAÍDA: Dr. Henrique Bastos\nNenhum outro visitante não residente registrado após este horário.' },
        { id: '2H', title: 'Rascunho de E-mail - Computador de Darlene Montês', content: 'PARA: henrique.bastos@email.com\nASSUNTO: MUDANÇA URGENTE - TESTAMENTO\nDATA: 14/06, 17:30\n(Este e-mail nunca foi enviado).\n"Henrique, decidi. A ambição de Ricardo se tornou um perigo e a irresponsabilidade de Verônica não tem cura. Quero que prepare uma nova minuta do meu testamento imediatamente. Remova ambos. James será o único herdeiro de 100% das ações das Empresas Montês."' },
        { id: '2I', title: 'Extrato Bancário - Afonso Pereira', content: 'BANCO CENTRAL DA CIDADE\nEXTRATO DE CONTA POUPANÇA: AFONSO PEREIRA\nDATA: 15/06/2025\nDESCRIÇÃO: DEPÓSITO EM ESPÉCIE\nVALOR: R$ 50.000,00' },
        { id: '2J', title: 'Fatura do Cartão - Sofia Montês', content: 'FATURA COM VENCIMENTO EM JULHO/2025\nDATA: 05/06\nESTABELECIMENTO: Loja "Jardim Secreto"\nDESCRIÇÃO: DIVERSOS JARDINAGEM\nVALOR: R$ 180,00\n(Nota de rodapé da loja anexa: Itens comprados - Luvas de jardinagem reforçadas, Tesouras de poda de precisão, Fertilizante para orquídeas.)' },
        { id: '2K', title: 'Recibo de Farmácia - Quarto de Clara Dias', content: 'FARMAVIDA - A SUA SAÚDE EM PRIMEIRO LUGAR\nDATA: 12/06/2025\n1x Lorazepam 2mg (Genérico) ........... R$ 25,00\n(Observação: O recibo foi encontrado no lixo. A receita médica correspondente não foi localizada).' },
        { id: '2L', title: 'Registros Telefônicos (14/06)', content: 'Aparelho de Darlene Montês:\n16:15 - RECEBIDA: Dr. Henrique Bastos (12 min)\n18:45 - RECEBIDA: Arthur Vasconcelos (1 min)\n20:10 - NÃO ATENDIDA: Leonardo Aguilar\n\nAparelho de Ricardo Montês:\n22:30 - REALIZADA: Dr. Henrique Bastos (45 seg)\n\nAparelho de Verônica Montês:\n20:05 - RECEBIDA: "Cobranças VIP" (5 min)\n21:50 - REALIZADA: "Agiota Anjo" (2 min)' },
        { id: '2M', title: 'Histórico Bancário - Leonardo Aguilar', content: 'PADRÃO DE TRANSAÇÕES - CONTA 45678-9\n\nMARÇO: Crédito de R$ 15.000,00 (Origem: D. MONTÊS)\nABRIL: Crédito de R$ 15.000,00 (Origem: D. MONTÊS)\nMAIO: Crédito de R$ 15.000,00 (Origem: D. MONTÊS)\nJUNHO: Nenhuma transação de crédito registrada da origem especificada.' }
    ],
    interrogations: [
      { suspect: 'Ricardo Montês', transcript: '(som de impaciência, tamborilando os dedos na mesa)...Vamos ser eficientes, por favor, meu tempo é limitado. Sim, eu já disse, estava em meu escritório. Estava no telefone, fechando os últimos detalhes da aquisição da Kenkō-sha, uma transação que, aliás, minha mãe vetou na semana passada. Ela chamava isso de \'prudência\', eu chamo de estagnação... A morte dela, embora trágica em nível pessoal, foi uma... liberação para a empresa. Quem pode se beneficiar? Olhem para a minha irmã. Verônica está afundada em dívidas... Quanto ao veneno, só sei o que a polícia comentou. Oleandro, não é? Irônico.' },
      { suspect: 'Verônica Montês', transcript: '(voz embargada, fungando)...Eu vim para cá tentar fazer as pazes. Juro. Achei que se ela me visse, se conversasse comigo... mas ela era um bloco de gelo. A última coisa que me disse foi: \'Sua presença nesta casa azeda o ar\'. E virou as costas. Então, sim, eu subi para o meu antigo quarto... Por volta das nove e meia, desci as escadas em silêncio... Foi quando eu vi Afonso na copa. Ele não me viu. Estava de costas, polindo uma bandeja de prata com uma fúria... contida. O corpo todo dele estava tenso... Ele parecia um homem prestes a explodir. Eu só peguei minha água e fugi. Matar minha mãe? Pelo quê? Pelo dinheiro que ela se certificou em testamento que eu nunca tocaria? Não faz sentido. Eu só queria... só queria minha mãe de volta.' },
      { suspect: 'Sofia Montês', transcript: '(tom calmo, quase terapêutico) ...É uma tragédia que abala a todos nós. Darlene era uma mulher de convicções... rígidas. Ela acreditava que sua maneira era a única, o que, naturalmente, criava atritos, especialmente com alguém tão vanguardista quanto Ricardo. Mas tudo vinha de um lugar de proteção, eu suponho. Naquela noite, eu me refugiei na minha estufa. É meu santuário. A beleza silenciosa das minhas orquídeas Phalaenopsis, o perfume sutil dos jasmins... é onde eu encontro paz. Fiquei lá até umas dez da noite, replantando algumas mudas. Depois, li uma revista no salão principal. Pobre Darlene, ela era tão particular com seus rituais. O chá noturno, por exemplo, tinha que ser servido naquela xícara específica de porcelana chinesa, aquela com o pequeno dragão dourado. Um detalhe bobo, talvez, mas que mostra como ela gostava de ordem. Afonso sabe disso melhor que ninguém. Ele é de uma lealdade impecável. Um verdadeiro relógio.' },
      { suspect: 'Afonso Pereira', transcript: '(voz baixa, quase um murmúrio) ...O serviço era minha vida. Quarenta anos. Eu vi os meninos crescerem. Naquela noite... foi como todas as outras noites. Tudo como sempre. Às nove e cinco, levei o chá de camomila para a Dona Darlene na biblioteca. Ela estava lendo, me agradeceu sem tirar os olhos do livro. Voltei para a copa. Sim, eu precisava de dinheiro. Minha neta... Lúcia... o tratamento é muito caro. Eu pedi à patroa. Pedi com o coração na mão. Ela me olhou e disse: ´´Afonso, sua dedicação é seu dever. Não confunda isso com crédito´´. Doeu. Doeu muito. Mas eu jamais... (pausa) ...era o meu dever. Eu a servi. Depois... fiquei na copa, sim. Organizando a prataria. Precisava manter as mãos ocupadas. Manter a mente ocupada. Não, não vi ninguém. Não falei com ninguém. Tudo como sempre, senhor. Tudo como sempre.' },
      { suspect: 'James Montês', transcript: 'Eu... eu não entendo como alguém pode fazer isso. Ela era difícil, sim, todos sabem. Controladora. Uma vez, quando eu era criança, pintei um quadro para ela, um campo de girassóis. Ela disse que a moldura era barata e que amarelo não combinava com a decoração da sala. (suspira) Mas era minha mãe. Naquela noite, eu estava no meu estúdio, a música estava alta, eu... me perco no trabalho. É a minha única fuga nesta casa. Quando subi para... para vê-la, para lhe dar boa noite como eu fazia às vezes, ela já... (pausa longa). O luto deles é uma peça de teatro. Ricardo fala de negócios, Sofia desfila sua elegância trágica, Verônica chora por si mesma. Ninguém está chorando por ela. Olhei para o Ricardo, para a Sofia... todos pareciam estar... atuando. O luto deles não me parece real. É por isso que chamei você. Alguém nesta casa é um monstro escondido atrás de uma máscara de civilidade.' },
      { suspect: 'Dr. Henrique Bastos', transcript: 'Minha relação com a Sra. Montês era estritamente profissional e de longa data. Na noite em questão, conforme minha agenda, discuti com ela alguns assuntos pendentes relativos à estrutura de governança do patrimônio Montês. Terminamos precisamente às 20:10. Minha saída foi registrada pela segurança. Sobre o conteúdo da conversa, o privilégio advogado-cliente me impede de comentar. Posso afirmar, em termos gerais, que a Sra. Montês era uma mulher de negócios astuta e estava sempre reavaliando suas posições e alianças, tanto no âmbito empresarial quanto familiar. Tais reavaliações, por sua natureza, podem gerar descontentamento em partes que se sintam preteridas. No entanto, não me cabe especular. Meu papel é executar as vontades de meus clientes dentro dos conformes da lei, não analisar as repercussões emocionais de tais atos.' },
      { suspect: 'Arthur Vasconcelos', transcript: 'Aquela mulher? Uma víbora! Uma aranha venenosa no centro da teia dela! Ela ia me destruir, e por prazer! Ela descobriu uma... manobra fiscal minha, algo que todo mundo no nosso meio faz, e decidiu usar isso para me devorar, para tomar minha empresa por centavos! Sim, eu fui até lá. Implorei. Tentei argumentar, ofereci um acordo. Ela riu na minha cara! Disse que \'o mercado precisa de uma limpeza\'. Saí de lá às sete da noite, vendo meu mundo desabar. Fui para o primeiro bar que encontrei, o \'Copos e Cinzas\'. Bebi uísque. Vários. Sozinho. Paguei em dinheiro e fui embora. Não lembro o nome do barman, não peguei recibo, eu estava tentando apagar o mundo, não registrar minha presença nele! Querem um suspeito? Procurem qualquer um que já tenha feito negócios com Darlene Montês. A fila vai ser grande.' },
      { suspect: 'Leonardo Aguilar', transcript: 'Eu na mansão? Que absurdo. Aquele lugar é um mausoléu de mau gosto. Eu tenho meu próprio apartamento, meu próprio ateliê, um espaço de criação. Darlene era... uma mecenas. Generosa, sim, mas com a sensibilidade de uma porta. Tivemos um desentendimento, claro. Ela queria que minha nova série fosse \'mais comercial\'. Tentar ditar a minha arte? É um insulto. Cortar meu financiamento? Um blefe patético para me controlar. Ela precisava de mim tanto quanto eu precisava do dinheiro dela. Eu era a única beleza na vida dela, o único toque de vanguarda. Naquela noite, eu estava imerso no meu processo criativo, trabalhando numa peça de bronze. É um trabalho intenso, solitário. O fogo, o metal... O tempo se torna irrelevante. Então, não, não tenho um \'álibi\'. A arte não se submete a relógios de ponto. Verifiquem meu telefone. Não vão encontrar nada. Eu estava em outro plano.' },
      { suspect: 'Clara Dias', transcript: '(voz quase inaudível, olhando para as próprias mãos) ...Eu só fazia meu trabalho. As vitaminas. Os comprimidos para dormir. Tudo na hora certa. A Sra. Darlene era muito... rígida. Com os horários, com as doses. Tudo tinha que ser exato. Meu turno acabou às 20:30. Exatamente. Eu fui para o meu quarto, sim. Tranquei a porta. Não, não saí de lá. Eu... eu estava cansada. Li um pouco e... não, eu acho que só tentei dormir. Não ouvi nada, não vi nada. A casa é grande, meu quarto fica longe. Ela era uma patroa exigente, sim, mas... eu não... eu não sei de nada. A farmácia? Ah... sim, eu compro meus remédios lá. Para dor de cabeça. Eu tenho muitas dores de cabeça. Por favor, eu não sei de nada. Só quero ficar fora disso.' },
    ],
    solution: {
      culpritId: 'sofia',
      method: 'Envenenamento por Oleandro, cujas folhas foram arrancadas do jardim, misturadas ao chá e servidas em uma xícara réplica para não usar o jogo de chá original da vítima.',
      motive: 'Sofia sentia-se diminuída por Darlene e temia perder seu status social e estilo de vida, especialmente após descobrir a intenção de Darlene de fazer de James o único herdeiro. Para garantir seu futuro através do controle de Ricardo sobre a fortuna, ela decidiu eliminar Darlene.'
    }
  }
};